[project]
name = "run-tracker-visualized"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gspread>=6.1.4",
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "oauth2client>=4.1.3",
    "pandas>=2.2.3",
]
